import styles from "@/Global.module.scss"
export const metadata = {
  title: 'Teuma SME',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={styles.body}>{children}</body>
    </html>
  )
}
